### ISSUE TITLE
Pause menu Bug

### ISSUE THREAD

**Issue by cavedwellerr** [palp/RAT-WARS#46]
**Pressing Pause button when the upgrade prompt is up breaks the pause**, the upgrade prompt becomes non-interactable a pausing again doesn't fix it.
You are able, however, to return to main menu and open "Options" menu.

I believe this is an issue of that tutorial project.

**Comment by palp** [comment]
I am pretty sure I fixed this when reworking the pause menu - double check when you get a chance.

**Comment by palp** [comment]
nope, I just repro'd again, not fixed
